version: '3.9'

services:

  mongo_db:
    container_name: db-container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    networks:
      - app-network


  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo_db:27017/sample-db
    networks:
      - app-network


volumes:
  mongo_db: {}

networks:
  app-network:
    driver: bridge
    




