apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-storage
  namespace: testing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

