apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: testing
spec:
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: testing
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 5000
  selector:
    app: node-app

