apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: testing
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        volumes:
          - name: mongo-storage
            persistentVolumeClaim:
              claimName: database-persistent-volume-claim
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-app
  namespace: testing
spec:
  serviceName: "node-app"
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 107534347551.dkr.ecr.ap-south-1.amazonaws.com/node-app:v1.${BUILD_ID}
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/sample-db"
      imagePullSecrets:
      - name: ecr-registry

